Firebat hacs patch 2 (#2)
* Update build-firmware.yaml

* Update build-firmware.yaml

* Update build-firmware.yaml

* Update build-firmware.yaml

* Update build-firmware.yaml

* Update build-firmware.yaml

* Update build-firmware.yaml

* Update build-firmware.yaml

* Update build-firmware.yaml

* Update build-firmware.yaml

* Update build-firmware.yaml

* Update board_configuration.cpp

* Add files via upload

* Rename prepend (1).txt to prepend.txt

* Update prepend.txt

* Add Spare Pins

* Update custom_firmware.yaml

* Update custom_firmware.yaml

* Update custom_firmware.yaml

* Update custom_firmware.yaml

* Update custom_firmware.yaml

diff --git a/.github/workflows/build-firmware.yaml b/.github/workflows/build-firmware.yaml
--- a/.github/workflows/build-firmware.yaml
+++ b/.github/workflows/build-firmware.yaml
@@ -16,7 +16,7 @@ on:
 
 jobs:
   build-firmware:
-    runs-on: ubuntu-latest-selfhost
+    runs-on: ubuntu-latest
 
     strategy:
       # Let all builds finish even if one fails early
@@ -24,152 +24,20 @@ jobs:
       matrix:
         include:
           # Board configurations
-          # - build-target: hellen72
-          #   folder: config/boards/hellen/hellen72
-          #   ini-file: fome_hellen72.ini
-
-          # - build-target: hellen81
-          #   folder: config/boards/hellen/hellen81
-          #   ini-file: fome_hellen81.ini
-
-          # - build-target: alphax-2chan
-          #   folder: config/boards/hellen/alphax-2chan
-          #   ini-file: fome_alphax-2chan.ini
-
-          # - build-target: alphax-4chan
-          #   folder: config/boards/hellen/alphax-4chan
-          #   ini-file: fome_alphax-4chan.ini
-
-          # - build-target: alphax-8chan
-          #   folder: config/boards/hellen/alphax-8chan
-          #   ini-file: fome_alphax-8chan.ini
-
-          # - build-target: harley81
-          #   folder: config/boards/hellen/harley81
-          #   ini-file: fome_harley81.ini
-
-        #   - build-target: small-can-board
-        #     folder: config/boards/hellen/small-can-board
-        #     ini-file: fome_small-can-board.ini
-
-          # - build-target: hellen88bmw
-          #   folder: config/boards/hellen/hellen88bmw
-          #   ini-file: fome_hellen88bmw.ini
-
-          # - build-target: hellen-nb1
-          #   folder: config/boards/hellen/hellen-nb1
-          #   ini-file: fome_hellen-nb1.ini
-
-          # - build-target: hellen-gm-e67
-          #   folder: config/boards/hellen/hellen-gm-e67
-          #   ini-file: fome_hellen-gm-e67.ini
-
-          # - build-target: hellenNA8_96
-          #   folder: config/boards/hellen/hellenNA8_96
-          #   ini-file: fome_hellenNA8_96.ini
-
-          # - build-target: hellenNA6
-          #   folder: config/boards/hellen/hellen64_miataNA6_94
-          #   ini-file: fome_hellenNA6.ini
-
-          # - build-target: hellen128
-          #  folder: config/boards/hellen/hellen128
-          #  ini-file: fome_hellen128.ini
-
-          # - build-target: hellen121vag
-          #   folder: config/boards/hellen/hellen121vag
-          #   ini-file: fome_hellen121vag.ini
-
-          # - build-target: hellen121nissan
-          #   folder: config/boards/hellen/hellen121nissan
-          #   ini-file: fome_hellen121nissan.ini
-
-          # - build-target: hellen-honda-k
-          #   folder: config/boards/hellen/hellen-honda-k
-          #   ini-file: fome_hellen-honda-k.ini
-
-          # - build-target: hellen154hyundai
-          #   folder: config/boards/hellen/hellen154hyundai
-          #   ini-file: fome_hellen154hyundai.ini
-
-          # - build-target: frankenso_na6
-          #   folder: config/boards/frankenso
-          #   ini-file: fome_frankenso_na6.ini
-
-          # - build-target: mre_f4
-          #   folder: config/boards/microrusefi
-          #   ini-file: fome_mre_f4.ini
-
-          # - build-target: mre_f7
-          #   folder: config/boards/microrusefi
-          #   ini-file: fome_mre_f7.ini
-
-          # - build-target: proteus_f4
-          #   folder: config/boards/proteus
-          #   ini-file: fome_proteus_f4.ini
-
-          # - build-target: proteus_f7
-          #   folder: config/boards/proteus
-          #   ini-file: fome_proteus_f7.ini
-
-          # - build-target: proteus_h7
-          #   folder: config/boards/proteus
-          #   ini-file: fome_proteus_h7.ini
-
-          # - build-target: stm32f429_nucleo
-          #   folder: config/boards/nucleo_f429
-          #   ini-file: fome_stm32f429_nucleo.ini
-
-          # - build-target: stm32f767_nucleo
-          #   folder: config/boards/nucleo_f767
-          #   ini-file: fome_stm32f767_nucleo.ini
-
-          # - build-target: stm32h743_nucleo
-          #   folder: config/boards/nucleo_h743
-          #   ini-file: fome_stm32h743_nucleo.ini
-
-          # - build-target: f407-discovery
-          #   folder: config/boards/f407-discovery
-          #   ini-file: fome_f407-discovery.ini
-
-        #   - build-target: core8
-        #     folder: config/boards/core8
-        #     ini-file: fome_core8.ini
-
-        #   - build-target: core48
-        #     folder: config/boards/core48
-        #     ini-file: fome_core48.ini
-
-          # - build-target: atlas
-          #   folder: config/boards/atlas
-          #   ini-file: fome_atlas.ini
-
-          # - build-target: tdg-pdm8
-          #   folder: config/boards/tdg-pdm8
-          #   ini-file: fome_tdg-pdm8.ini
           
-           - build-target: shoefi
-             folder: config/boards/shoefi
-             ini-file: fome_shoefi.ini
+          - build-target: shoefi
+            folder: config/boards/shoefi
+            ini-file: fome_shoefi.ini
 
     steps:
-    - name: Check branch name
-      if: ${{ contains(github.ref_name, '.') }}
-      run: echo '::error::Branch names must not contain ".", this breaks firmware autoupdates.' && exit 1
+    #- name: Check branch name
+    #  if: ${{ contains(github.ref_name, '.') }}
+    #  run: echo '::error::Branch names must not contain ".", this breaks firmware autoupdates.' && exit 1
 
     - name: Set run condition variables
       run: |
-        if [ "${{github.repository}}" = "FOME-Tech/fome-fw" ]\
-        && [ "${{github.event_name}}" = "push" ]\
-        && [ "${{github.ref}}" = "refs/heads/master" ]\
-        || [ "${{toJSON(inputs.do_upload)}}" = "true" ]; then
-          echo "full=true" >> $GITHUB_ENV
-          echo "upload=true" >> $GITHUB_ENV
-        elif [ "${{github.event_name}}" = "push" ]\
-        && [ "${{github.ref}}" = "refs/heads/master" ]; then
-          echo "full=true" >> $GITHUB_ENV
-        fi
-
+        echo "full=true" >> $GITHUB_ENV
+        echo "upload=true" >> $GITHUB_ENV
     - uses: actions/checkout@v6
       with:
         submodules: true
@@ -179,13 +47,18 @@ jobs:
     #     distribution: 'zulu'
     #     java-version: '8'
 
-    # - name: Install multilib, mingw, sshpass and mtools
-    #   working-directory: ./.github/workflows/
-    #   run: |
-    #     sudo ./add-ubuntu-latest-apt-mirrors.sh
-    #     sudo apt-get install gcc-multilib g++-multilib g++-mingw-w64 gcc-mingw-w64 sshpass mtools
-    #     sudo apt-get install zip
-    #     sudo apt-get install dosfstools
+    - name: Install multilib, mingw, sshpass and mtools
+      working-directory: ./.github/workflows/
+      run: |
+        sudo ./add-ubuntu-latest-apt-mirrors.sh
+        sudo apt-get install gcc-multilib g++-multilib g++-mingw-w64 gcc-mingw-w64 sshpass mtools
+        sudo apt-get install zip
+        sudo apt-get install dosfstools
+
+     #- name: Install mtools
+     #  run: |
+     #   python -m pip install --upgrade pip
+     #   pip install mtools
 
     # Build the firmware!
     - name: Build Firmware
